/**
 * CAPA DE DATOS DE DEMOSTRACIÓN
 * ------------------------------------------------------------------
 * Este archivo simula la respuesta de la Shopify Storefront API.
 * Cada objeto de `PRODUCTS` usa los mismos campos que expondría
 * Shopify (title, handle, vendor, tags, images, variants, price,
 * compareAtPrice, metafields...) para que, al conectar la tienda
 * real, baste con sustituir `PRODUCTS` por el resultado de una
 * query GraphQL a Shopify sin tocar el resto del front-end.
 *
 * Ejemplo de sustitución futura:
 *   const PRODUCTS = await storefrontClient.query(PRODUCTS_QUERY);
 *
 * Algunas fotos de producto se han sustituido por imágenes reales
 * extraídas del catálogo público de victorso.com (misma tienda,
 * fines de maquetación) para que la demo se vea más fiel; el resto
 * sigue usando placeholders de picsum.photos.
 * ------------------------------------------------------------------
 */

const CATEGORIES = [
  { slug: "dj", title: "Equipos DJ", icon: "sliders", image: "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/6/7/8/1200x1200_q100_png9_cr0_fix1/CDJ-1500X_prm_angle_260611.jpg" },
  { slug: "sonido", title: "Sonido Profesional", icon: "speaker", image: "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/0/5/1200x1200_q100_png9_cr0_fix1/001_ART-915-A-front.jpg" },
  { slug: "estudio", title: "Material de Estudio", icon: "mic", image: "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/7/6/1200x1200_q100_png9_cr0_fix1/controlador-ableton-live-akai-apc64.jpg" },
  { slug: "auriculares", title: "Auriculares", icon: "headphones", image: "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/1/2/1200x1200_q100_png9_cr0_fix1/sennheiser-hd400-1-jpg.jpg" },
  { slug: "cables", title: "Cables", icon: "plug", image: "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/3/0/1200x1200_q100_png9_cr0_fix1/11.jpg" },
  { slug: "flightcases", title: "Flight-Cases y Bolsas", icon: "suitcase", image: "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/6/8/0/1200x1200_q100_png9_cr0_fix1/AlphaTheta-DJC-AN-BAG-2.jpg" },
  { slug: "outlet", title: "Outlet", icon: "tag", image: "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/6/8/1200x1200_q100_png9_cr0_fix1/alphatheta-euphonia1.jpg" },
];

/** Logos reales extraídos del catálogo público de victorso.com. */
const BRANDS = [
  { name: "Pioneer DJ", slug: "pioneer-dj", featured: true, website: "https://www.pioneerdj.com", logo: "https://cloudflare.shopincdn.ovh/victorso/cache/images/165x83_q100_png9_cr0_fix1/pioneer-dj.png",
    description: "El estándar mundial en cabinas de DJ profesionales. Pioneer DJ equipa las salas y festivales más importantes del planeta, y es la marca en la que más confiamos en Victor So Professional." },
  { name: "AlphaTheta", slug: "alphatheta", featured: true, website: "https://www.alphatheta.com", logo: "https://cloudflare.shopincdn.ovh/victorso/cache/images/imagenes/logosmarcas2/165x83_q100_png9_cr0_fix1/AlphaTheta_logo_Horizontal_k.jpg",
    description: "La nueva marca del grupo Pioneer DJ / TAG Sound, enfocada en innovación para DJs: sistemas todo en uno, monitores de estudio y equipos portátiles de última generación." },
  { name: "Walkasse", slug: "walkasse", featured: true, website: "https://www.walkasse.com", logo: "assets/logo-walkasse.jpg",
    description: "Fabricante especializado en flight-cases y bolsas de transporte a medida, pensados para proteger equipos de sonido e iluminación en giras y eventos." },
  { name: "RCF", slug: "rcf", featured: true, website: "https://www.rcf.it", logo: "https://cloudflare.shopincdn.ovh/victorso/cache/images/imagenes/logosMarcas/165x83_q100_png9_cr0_fix1/logo_rcf.jpg",
    description: "Fabricante italiano con más de 70 años de historia en sonido profesional, presente en salas de conciertos, teatros y eventos en directo de todo el mundo." },
  { name: "Yamaha", slug: "yamaha", featured: true, website: "https://www.yamaha.com", logo: "https://cloudflare.shopincdn.ovh/victorso/cache/images/imagenes/logosMarcas/165x83_q100_png9_cr0_fix1/285_Victorso.jpg",
    description: "Uno de los grandes nombres de la electrónica musical, con altavoces y equipos de sonido conocidos por su fiabilidad y calidad de fabricación." },
  { name: "QSC", slug: "qsc", featured: true, website: "https://www.qsc.com", logo: "https://cloudflare.shopincdn.ovh/victorso/cache/images/imagenes/logosMarcas/165x83_q100_png9_cr0_fix1/qsc_logo.jpg",
    description: "Marca americana referente en altavoces activos y sistemas de sonido para instalaciones fijas, salas de conciertos y giras profesionales." },
  { name: "Rode", slug: "rode", featured: true, website: "https://www.rode.com", logo: "https://cloudflare.shopincdn.ovh/victorso/cache/images/imagenes/logosMarcas/165x83_q100_png9_cr0_fix1/rode_logo.png",
    description: "Fabricante australiano de micrófonos de estudio y grabación, muy valorado por creadores de contenido y estudios por su calidad de sonido y precio." },
  { name: "Focusrite", slug: "focusrite", featured: true, website: "https://focusrite.com", logo: "https://cloudflare.shopincdn.ovh/victorso/cache/images/imagenes/logosMarcas/165x83_q100_png9_cr0_fix1/focusrite_logo.jpg",
    description: "Interfaces de audio de referencia para producción musical en casa y en estudio, con la gama Scarlett como estándar de entrada al mundo profesional." },
  { name: "Sennheiser", slug: "sennheiser", featured: true, website: "https://www.sennheiser.com", logo: "https://cloudflare.shopincdn.ovh/victorso/cache/images/imagenes/logosmarcas2/165x83_q100_png9_cr0_fix1/senheiser.png",
    description: "Marca alemana centenaria en audio profesional, reconocida mundialmente por sus auriculares y micrófonos de altísima fidelidad." },
  { name: "Alesis", slug: "alesis", website: "https://www.alesis.com",
    description: "Marca americana especializada en baterías electrónicas, teclados, controladores MIDI y equipos de grabación." },
  { name: "Allen & Heath", slug: "allen-heath", website: "https://www.allen-heath.com",
    description: "Fabricante británico de mesas de mezclas analógicas y digitales para directo, instalación y DJ, con más de 50 años de historia." },
  { name: "Antelope Audio", slug: "antelope-audio", website: "https://en.antelopeaudio.com",
    logo: "assets/logos/antelope-audio.jpg",
    description: "Especialista en interfaces de audio, relojes maestros y micrófonos modelados de alta gama para estudio." },
  { name: "Arkaos", slug: "arkaos", website: "https://vj.arkaos.com",
    description: "Software de referencia para VJs, servidores de medios y mapping de LED usado en conciertos y eventos desde 1996." },
  { name: "Audient", slug: "audient", website: "https://audient.com",
    logo: "assets/logos/audient.png",
    description: "Fabricante británico de interfaces de audio, consolas y preamplificadores muy valorados en estudios de grabación." },
  { name: "Audio-Technica", slug: "audio-technica", website: "https://www.audio-technica.com",
    logo: "assets/logos/audio-technica.svg",
    description: "Fabricante japonés de micrófonos, auriculares y giradiscos con décadas de prestigio en audio profesional y doméstico." },
  { name: "Audiolab", slug: "audiolab", website: "https://www.audiolab.co.uk",
    description: "Marca británica de alta fidelidad especializada en amplificadores, reproductores y DACs para audiófilos." },
  { name: "Auralex", slug: "auralex", website: "https://auralex.com",
    description: "Líder en tratamiento acústico para estudios: espuma acústica, trampas de graves y difusores." },
  { name: "AVID", slug: "avid", website: "https://www.avid.com",
    logo: "assets/logos/avid.png",
    description: "Creadores de Pro Tools, el estándar de la industria en estaciones de trabajo de audio digital (DAW)." },
  { name: "Bitwig", slug: "bitwig", website: "https://www.bitwig.com",
    logo: "assets/logos/bitwig.svg",
    description: "Estación de trabajo de audio digital alemana pensada tanto para producción en estudio como para actuación en directo." },
  { name: "Dbx", slug: "dbx", website: "https://dbxpro.com",
    logo: "assets/logos/dbx.png",
    description: "Marca americana de referencia en procesadores de dinámica: compresores, limitadores y puertas de ruido." },
  { name: "DJBAG.PRO", slug: "djbag-pro", website: null,
    description: "Marca especializada en mochilas y bolsas de transporte diseñadas por DJs para proteger controladoras y auriculares en la carretera." },
  { name: "Electro-Voice", slug: "electro-voice", website: "https://www.electrovoice.com",
    logo: "assets/logos/electro-voice.svg",
    description: "Fabricante americano fundado en 1930, referencia en altavoces y micrófonos para sonido en directo e instalaciones." },
  { name: "GAPLASA", slug: "gaplasa", website: "https://gaplasapro.com",
    logo: "assets/logos/gaplasa.jpg",
    description: "Distribuidor español de sonido profesional, representante de marcas como Bose Professional y Clockaudio." },
  { name: "Gravity", slug: "gravity", website: null,
    description: "Marca del grupo Adam Hall especializada en soportes y trípodes para altavoces, micrófonos, teclados e iluminación." },
  { name: "Gretsch", slug: "gretsch", website: "https://www.gretsch.com",
    description: "Firma histórica americana de guitarras y baterías, con un sonido característico reconocido desde hace más de un siglo." },
  { name: "Konig & Meyer", slug: "konig-meyer", website: "https://www.k-m.de",
    logo: "assets/logos/konig-meyer.png",
    description: "Fabricante alemán con más de 75 años de experiencia en soportes para micrófonos, altavoces, teclados e instrumentos." },
  { name: "korg", slug: "korg", website: "https://www.korg.com",
    description: "Compañía japonesa pionera en sintetizadores, pianos digitales, afinadores y procesadores de audio." },
  { name: "KS technology", slug: "ks-technology", website: "https://ks-audio.com",
    description: "Fabricante alemán de sistemas de altavoces profesionales para salas, clubes, instalaciones y grandes eventos." },
  { name: "M-AUDIO", slug: "m-audio", website: "https://www.m-audio.com",
    logo: "assets/logos/m-audio.jpg",
    description: "Marca de interfaces de audio, teclados MIDI y monitores de estudio orientada a la producción musical doméstica y profesional." },
  { name: "Magma", slug: "magma", website: "https://www.magma-bags.de",
    logo: "assets/logos/magma.png",
    description: "Fabricante alemán de bolsas y flight-cases a medida para controladoras, mesas de mezclas y equipos de DJ." },
  { name: "MAGNETRON S.A.", slug: "magnetron", website: "https://www.magnetron.es",
    description: "Distribuidor español de audio profesional, representante de marcas como Sennheiser, Neumann y FBT." },
  { name: "Native Instruments", slug: "native-instruments", website: "https://www.native-instruments.com",
    logo: "assets/logos/native-instruments.svg",
    description: "Referencia en software y hardware para producción musical y DJ, creadores de Traktor y Komplete." },
  { name: "Neumann", slug: "neumann", website: "https://www.neumann.com",
    logo: "assets/logos/neumann.png",
    description: "Fabricante alemán de micrófonos de estudio desde 1928, sinónimo de calidad de grabación de referencia mundial." },
  { name: "Neutrik", slug: "neutrik", website: "https://www.neutrik.com",
    logo: "assets/logos/neutrik.svg",
    description: "Líder mundial en conectores de audio profesional, como los conectores XLR y speakON." },
  { name: "OQAN", slug: "oqan", website: "https://oqanmusic.com",
    logo: "assets/logos/oqan.png",
    description: "Marca española de instrumentos musicales y accesorios de sonido con una relación calidad-precio muy competitiva." },
  { name: "Palmer", slug: "palmer", website: "https://www.palmer-germany.com",
    logo: "assets/logos/palmer.png",
    description: "Fabricante alemán conocido por sus cajas DI y equipos de re-amplificación para estudio y directo." },
  { name: "PD-Connex", slug: "pd-connex", website: null,
    description: "Gama de cables y conectores de audio, iluminación y alimentación para uso profesional y doméstico." },
  { name: "PlayDifferently", slug: "playdifferently", website: "https://playdifferently.org",
    logo: "assets/logos/playdifferently.jpg",
    description: "Marca creada por Andy Rigby-Jones junto a Richie Hawtin, autora del icónico mixer analógico MODEL 1." },
  { name: "Presonus", slug: "presonus", website: "https://www.presonus.com",
    logo: "assets/logos/presonus.png",
    description: "Fabricante americano de interfaces de audio, mezcladores y monitores, creadores del DAW Studio One." },
  { name: "RANE_DJ", slug: "rane", website: "https://www.rane.com",
    logo: "assets/logos/rane.png",
    description: "Marca de referencia en mixers y controladoras DJ de altísima gama, utilizada por DJs profesionales de todo el mundo." },
  { name: "RME", slug: "rme", website: "https://rme-audio.de",
    description: "Fabricante alemán de interfaces de audio y conversores reconocido por su estabilidad y latencia mínima." },
  { name: "Roline", slug: "roline", website: "https://theroline.com",
    logo: "assets/logos/roline.jpg",
    description: "Marca de cables y accesorios de conectividad para instalaciones audiovisuales y de red." },
  { name: "Samson", slug: "samson", website: "https://samsontech.com",
    logo: "assets/logos/samson.jpg",
    description: "Fabricante americano de micrófonos, sistemas inalámbricos y monitores para directo y estudio." },
  { name: "Softube", slug: "softube", website: "https://www.softube.com",
    logo: "assets/logos/softube.svg",
    description: "Compañía sueca de plugins de audio de altísima calidad, en colaboración con marcas históricas como SSL o Tube-Tech." },
  { name: "Sonifex", slug: "sonifex", website: "https://www.sonifex.co.uk",
    logo: "assets/logos/sonifex.png",
    description: "Fabricante británico de equipos de audio para radio y televisión desde 1969." },
  { name: "Sony", slug: "sony", website: "https://pro.sony",
    logo: "assets/logos/sony.svg",
    description: "Multinacional japonesa con una amplia gama de soluciones de audio profesional para producción y directo." },
  { name: "Stanton", slug: "stanton", website: "https://www.stantondj.com",
    description: "Marca histórica del mundo DJ, pionera en giradiscos, cápsulas y mixers para scratch y turntablism." },
  { name: "Superlux", slug: "superlux", website: "https://en.superlux.com.tw",
    description: "Fabricante taiwanés de micrófonos y auriculares con una excelente relación calidad-precio." },
  { name: "Synq", slug: "synq", website: "https://synq-audio.com",
    logo: "assets/logos/synq.png",
    description: "Marca europea de equipos de sonido para instalación y DJ: amplificadores, altavoces y mixers." },
  { name: "Tannoy", slug: "tannoy", website: "https://www.tannoy.com",
    logo: "assets/logos/tannoy.svg",
    description: "Fabricante británico de altavoces fundado en 1926, con un legado reconocido en sonorización profesional." },
  { name: "Tascam", slug: "tascam", website: "https://tascam.com",
    logo: "assets/logos/tascam.svg",
    description: "Marca japonesa histórica en grabadores multipista y de campo para estudio, broadcast y producción audiovisual." },
  { name: "Tc electronic", slug: "tc-electronic", website: "https://www.tcelectronic.com",
    logo: "assets/logos/tc-electronic.svg",
    description: "Fabricante danés de efectos, procesadores e interfaces de audio de gran prestigio entre músicos y estudios." },
  { name: "Tc Helicon", slug: "tc-helicon", website: "https://www.tc-helicon.com",
    description: "Especialista en procesadores vocales, armonizadores y micrófonos para cantantes en directo y estudio." },
  { name: "Technics", slug: "technics", website: "https://www.technics.com",
    logo: "assets/logos/technics.svg",
    description: "Marca japonesa creadora del legendario giradiscos SL-1200, estándar mundial del DJ profesional." },
  { name: "Tecshow", slug: "tecshow", website: null,
    description: "Marca de equipos de sonido activo e iluminación DMX orientada al mercado profesional y de eventos." },
  { name: "teenage engineering", slug: "teenage-engineering", website: "https://teenage.engineering",
    description: "Diseñadora sueca de sintetizadores y grooveboxes de culto, reconocida por su diseño minimalista y su sonido único." },
  { name: "Turbosound", slug: "turbosound", website: "https://www.turbosound.com",
    description: "Fabricante de altavoces profesionales para sonido en directo, instalaciones y sistemas de línea de array." },
  { name: "Udg", slug: "udg", website: "https://udggear.com",
    description: "Marca líder en bolsas y maletas de transporte para DJs, conocida como 'Ultimate DJ Gear'." },
  { name: "Universal audio", slug: "universal-audio", website: "https://www.uaudio.com",
    logo: "assets/logos/universal-audio.png",
    description: "Referencia mundial en interfaces de audio y plugins UAD con emulaciones analógicas de equipos de estudio clásicos." },
  { name: "work", slug: "work-pro", website: "https://www.workpro.es",
    logo: "assets/logos/work-pro.png",
    description: "Marca de Equipson especializada en altavoces y sistemas de sonido profesional para instalación fija y portátil." },
  { name: "ZENTRALMEDIA", slug: "zentralmedia", website: "https://www.zentralmedia.com",
    description: "Distribuidor español de tecnología musical, audio profesional, DJ e iluminación para instalación." },
  { name: "Zomo", slug: "zomo", website: "https://www.zomo.de",
    logo: "assets/logos/zomo.png",
    description: "Marca alemana especializada en bolsas, flight-cases y accesorios de transporte para equipos de DJ." },
];

/** Genera un array de variantes con precio derivado del precio base */
function buildVariants(base, options) {
  return options.map((opt, i) => ({
    id: `${base.id}-v${i + 1}`,
    title: opt.title,
    price: opt.price ?? base.price,
    compareAtPrice: opt.compareAtPrice ?? base.compareAtPrice ?? null,
    sku: `${base.id.toUpperCase()}-${i + 1}`,
    available: opt.available !== false,
  }));
}

const RAW_PRODUCTS = [
  {
    id: "cdj3000", handle: "pioneer-dj-cdj-3000", title: "Pioneer DJ CDJ-3000 Reproductor Multimedia",
    vendor: "Pioneer DJ", category: "dj", price: 2299, compareAtPrice: null,
    tags: ["dj", "reproductor", "profesional", "Pioneer DJ"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/6/7/8/1200x1200_q100_png9_cr0_fix1/CDJ-1500X_prm_angle_260611.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/6/7/8/1200x1200_q100_png9_cr0_fix1/CDJ-1500X_prm_angle_260611.jpg"],
    optionName: "Formato",
    options: [{ title: "Unidad individual" }, { title: "Pack x2 (ahorra 150€)", price: 4448 }],
    rating: 4.9, reviewsCount: 128,
    description: "El estándar de la industria en cabinas profesionales. Pantalla táctil de alta resolución, control de tempo de alta precisión y compatibilidad con rekordbox y Serato.",
    specs: [
      ["Pantalla", "9\" táctil a color"],
      ["Formatos soportados", "MP3, AAC, WAV, AIFF, FLAC"],
      ["Conectividad", "USB, LAN, Wi-Fi"],
      ["Rango de Pitch", "±6/±10/±16/±100%"],
      ["Peso", "5.5 kg"],
      ["Dimensiones", "360 x 415 x 107 mm"],
    ],
  },
  {
    id: "djm-a9", handle: "pioneer-dj-djm-a9", title: "Pioneer DJ DJM-A9 Mezclador de 4 Canales",
    vendor: "Pioneer DJ", category: "dj", price: 2599, compareAtPrice: 2799,
    tags: ["dj", "mezclador", "profesional", "Pioneer DJ", "oferta"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/1/6/1200x1200_q100_png9_cr0_fix1/1.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/1/6/1200x1200_q100_png9_cr0_fix1/1.jpg"],
    optionName: "Formato", options: [{ title: "Unidad individual" }],
    rating: 4.8, reviewsCount: 76,
    description: "Mezclador insignia con conversores A/D de 64 bits y sonido de calidad estudio para las cabinas más exigentes.",
    specs: [
      ["Canales", "4"],
      ["Conversión", "64-bit A/D"],
      ["Ecualizador", "3 bandas + Isolator"],
      ["Efectos", "Beat FX + Sound Color FX"],
      ["Peso", "6.4 kg"],
    ],
  },
  {
    id: "omnis-duo", handle: "alphatheta-omnis-duo", title: "AlphaTheta OMNIS-DUO Sistema Todo en Uno",
    vendor: "AlphaTheta", category: "dj", price: 1899, compareAtPrice: null, isNew: true,
    tags: ["dj", "todo-en-uno", "AlphaTheta"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/6/6/1200x1200_q100_png9_cr0_fix1/alphatheta-omnis-duo.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/6/6/1200x1200_q100_png9_cr0_fix1/alphatheta-omnis-duo.jpg"],
    optionName: "Color",
    options: [{ title: "Negro" }, { title: "Blanco" }],
    rating: 4.7, reviewsCount: 41,
    description: "Sistema portátil todo en uno con altavoces integrados, batería recargable y streaming de música. Ideal para movilidad.",
    specs: [
      ["Batería", "Hasta 8 horas"],
      ["Altavoces", "2 x 60W integrados"],
      ["Conectividad", "Bluetooth, USB, Wi-Fi"],
      ["Streaming", "Compatible con Beatport, SoundCloud"],
      ["Peso", "12.8 kg"],
    ],
  },
  {
    id: "xdj-rx3", handle: "pioneer-dj-xdj-rx3", title: "Pioneer DJ XDJ-RX3 Controlador Standalone",
    vendor: "Pioneer DJ", category: "dj", price: 1799, compareAtPrice: null, isNew: true,
    tags: ["dj", "controlador", "Pioneer DJ"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/4/6/1200x1200_q100_png9_cr0_fix1/OPUS-QUAD_prm_top_230130.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/4/6/1200x1200_q100_png9_cr0_fix1/OPUS-QUAD_prm_top_230130.jpg"],
    optionName: "Formato", options: [{ title: "Unidad individual" }],
    rating: 4.8, reviewsCount: 63,
    description: "Controlador standalone de 2 canales con gran pantalla táctil, no requiere ordenador para actuar.",
    specs: [
      ["Canales", "2"],
      ["Pantalla", "10.1\" táctil"],
      ["Entradas", "USB, micro x2, línea/phono"],
      ["Software", "rekordbox (incluido)"],
      ["Peso", "6.4 kg"],
    ],
  },
  {
    id: "wego4", handle: "alphatheta-wego4", title: "AlphaTheta WeGO4 Altavoz Portátil DJ",
    vendor: "AlphaTheta", category: "dj", price: 449, compareAtPrice: null, isNew: true,
    tags: ["dj", "altavoz-portatil", "AlphaTheta"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/6/7/1200x1200_q100_png9_cr0_fix1/alphatheta-wave-eight.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/6/7/1200x1200_q100_png9_cr0_fix1/alphatheta-wave-eight.jpg"],
    optionName: "Color",
    options: [{ title: "Negro" }, { title: "Rojo" }],
    rating: 4.5, reviewsCount: 29,
    description: "Altavoz portátil con batería para sesiones DJ en cualquier lugar, resistente a salpicaduras.",
    specs: [
      ["Potencia", "100W"],
      ["Batería", "Hasta 10 horas"],
      ["Resistencia", "IPX4 (salpicaduras)"],
      ["Conectividad", "Bluetooth 5.0"],
      ["Peso", "4.9 kg"],
    ],
  },
  {
    id: "art315a", handle: "rcf-art-315-a", title: "RCF ART 315-A Altavoz Activo 15\"",
    vendor: "RCF", category: "sonido", price: 699, compareAtPrice: null,
    tags: ["sonido", "altavoz-activo", "RCF"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/0/5/1200x1200_q100_png9_cr0_fix1/001_ART-915-A-front.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/0/5/1200x1200_q100_png9_cr0_fix1/001_ART-915-A-front.jpg"],
    optionName: "Formato",
    options: [{ title: "Unidad" }, { title: "Pareja (ahorra 40€)", price: 1358 }],
    rating: 4.6, reviewsCount: 54,
    description: "Altavoz activo de 15\" con amplificación clase D, ideal para eventos medianos y refuerzo sonoro.",
    specs: [
      ["Potencia", "800W pico"],
      ["Woofer", "15\""],
      ["SPL Máximo", "128 dB"],
      ["Entradas", "XLR/Jack combo"],
      ["Peso", "16.4 kg"],
    ],
  },
  {
    id: "dxr12", handle: "yamaha-dxr12-mkii", title: "Yamaha DXR12 MkII Altavoz Activo",
    vendor: "Yamaha", category: "sonido", price: 799, compareAtPrice: 899,
    tags: ["sonido", "altavoz-activo", "Yamaha", "oferta"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/4/1/3/1200x1200_q100_png9_cr0_fix1/Alto_TS412-Angle-Right.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/4/1/3/1200x1200_q100_png9_cr0_fix1/Alto_TS412-Angle-Right.jpg"],
    optionName: "Formato", options: [{ title: "Unidad" }],
    rating: 4.7, reviewsCount: 88,
    description: "Referencia en sonorización profesional, con procesado DSP integrado y respuesta de frecuencia optimizada.",
    specs: [
      ["Potencia", "1100W"],
      ["Woofer", "12\""],
      ["DSP", "Sí, con presets"],
      ["SPL Máximo", "132 dB"],
      ["Peso", "18.7 kg"],
    ],
  },
  {
    id: "k12-2", handle: "qsc-k12-2", title: "QSC K12.2 Altavoz Activo",
    vendor: "QSC", category: "sonido", price: 899, compareAtPrice: null,
    tags: ["sonido", "altavoz-activo", "QSC"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/5/7/1200x1200_q100_png9_cr0_fix1/COM-3737_D82_S1ProPlus_01_Tilted_Hero_IJ_RGB-2000px.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/5/7/1200x1200_q100_png9_cr0_fix1/COM-3737_D82_S1ProPlus_01_Tilted_Hero_IJ_RGB-2000px.jpg"],
    optionName: "Formato", options: [{ title: "Unidad" }],
    rating: 4.8, reviewsCount: 47,
    description: "Altavoz activo de gama alta con control DSP vía app y diseño ultraligero para giras.",
    specs: [
      ["Potencia", "2000W pico"],
      ["Woofer", "12\""],
      ["Control", "App QSC (iOS/Android)"],
      ["SPL Máximo", "132 dB"],
      ["Peso", "14.5 kg"],
    ],
  },
  {
    id: "sub8004", handle: "rcf-sub-8004-as", title: "RCF SUB 8004-AS Subwoofer Activo",
    vendor: "RCF", category: "sonido", price: 1199, compareAtPrice: null,
    tags: ["sonido", "subwoofer", "RCF"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/4/1/0/1200x1200_q100_png9_cr0_fix1/Alto-ts318s.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/4/1/0/1200x1200_q100_png9_cr0_fix1/Alto-ts318s.jpg"],
    optionName: "Formato", options: [{ title: "Unidad" }],
    rating: 4.7, reviewsCount: 22,
    description: "Subwoofer activo de 18\" con gran presión sonora, imprescindible para refuerzo de graves en directo.",
    specs: [
      ["Potencia", "1400W pico"],
      ["Altavoz", "18\""],
      ["SPL Máximo", "133 dB"],
      ["Preset", "Cardioide seleccionable"],
      ["Peso", "36 kg"],
    ],
  },
  {
    id: "nt1", handle: "rode-nt1", title: "Rode NT1 Micrófono de Condensador",
    vendor: "Rode", category: "estudio", price: 249, compareAtPrice: null,
    tags: ["estudio", "microfono", "Rode"],
    images: ["https://picsum.photos/seed/nt1-a/900/900", "https://picsum.photos/seed/nt1-b/900/900"],
    optionName: "Formato",
    options: [{ title: "Solo micrófono" }, { title: "Kit con interfaz", price: 349 }],
    rating: 4.9, reviewsCount: 61,
    description: "Micrófono de condensador de estudio con el ruido propio más bajo de su categoría, ideal para voces e instrumentos.",
    specs: [
      ["Patrón polar", "Cardioide"],
      ["Ruido propio", "4.5 dBA"],
      ["Conexión", "XLR"],
      ["Incluye", "Araña antivibración, funda"],
      ["Peso", "326 g"],
    ],
  },
  {
    id: "scarlett2i2", handle: "focusrite-scarlett-2i2", title: "Focusrite Scarlett 2i2 Interfaz de Audio",
    vendor: "Focusrite", category: "estudio", price: 179, compareAtPrice: null,
    tags: ["estudio", "interfaz-audio", "Focusrite"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/0/1/1/1200x1200_q100_png9_cr0_fix1/MOSC0034-Focusrite_Scarlett_4i4_4th_Gen_Elevated__89814.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/0/1/1/1200x1200_q100_png9_cr0_fix1/focusrite-scarlett-4i4-gen-4.jpg"],
    optionName: "Generación",
    options: [{ title: "3ª Generación" }, { title: "4ª Generación", price: 219 }],
    rating: 4.8, reviewsCount: 152,
    description: "La interfaz de audio más popular del mundo para home studio, con preamplificadores de micrófono galardonados.",
    specs: [
      ["Entradas", "2 combo XLR/Jack"],
      ["Salidas", "2 línea + auriculares"],
      ["Resolución", "24-bit / 192kHz"],
      ["Conexión", "USB-C"],
      ["Peso", "0.6 kg"],
    ],
  },
  {
    id: "hdjcue1-mon", handle: "alphatheta-hdj-cue1-monitores", title: "AlphaTheta VM-70 Monitores de Estudio (par)",
    vendor: "AlphaTheta", category: "estudio", price: 349, compareAtPrice: null,
    tags: ["estudio", "monitores", "AlphaTheta"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/3/6/7/1200x1200_q100_png9_cr0_fix1/pioneer-dj-vm-50-BONA.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/3/6/7/1200x1200_q100_png9_cr0_fix1/pioneer-dj-vm-50-BONA.jpg"],
    optionName: "Formato", options: [{ title: "Par (2 unidades)" }],
    rating: 4.6, reviewsCount: 18,
    description: "Monitores de estudio activos de campo cercano, diseñados junto a ingenieros de sonido profesionales.",
    specs: [
      ["Potencia", "2 x 45W"],
      ["Woofer", "5.25\""],
      ["Respuesta", "45Hz - 40kHz"],
      ["Entradas", "XLR, RCA, Jack"],
      ["Peso (par)", "8.4 kg"],
    ],
  },
  {
    id: "hdjx10", handle: "pioneer-dj-hdj-x10", title: "Pioneer DJ HDJ-X10 Auriculares DJ Profesionales",
    vendor: "Pioneer DJ", category: "auriculares", price: 279, compareAtPrice: null,
    tags: ["auriculares", "dj", "Pioneer DJ"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/3/4/4/4/1200x1200_q100_png9_cr0_fix1/VAAKGK181DJ.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/3/4/4/4/1200x1200_q100_png9_cr0_fix1/VAAKGK181DJ.jpg"],
    optionName: "Color",
    options: [{ title: "Negro" }, { title: "Plata" }, { title: "Azul" }],
    rating: 4.8, reviewsCount: 94,
    description: "Auriculares de referencia profesional con driver de 50mm y aislamiento acústico superior para cabina.",
    specs: [
      ["Driver", "50 mm"],
      ["Impedancia", "32 Ω"],
      ["Respuesta", "5Hz - 30kHz"],
      ["Plegable", "Sí, giro 90°"],
      ["Peso", "310 g"],
    ],
  },
  {
    id: "hdjcue1", handle: "alphatheta-hdj-cue1", title: "AlphaTheta HDJ-CUE1 Auriculares DJ",
    vendor: "AlphaTheta", category: "auriculares", price: 89, compareAtPrice: 109,
    tags: ["auriculares", "dj", "AlphaTheta", "oferta"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/1/2/1200x1200_q100_png9_cr0_fix1/sennheiser-hd400-1-jpg.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/1/2/1200x1200_q100_png9_cr0_fix1/sennheiser-hd400-1-jpg.jpg"],
    optionName: "Color",
    options: [{ title: "Negro" }, { title: "Blanco" }],
    rating: 4.4, reviewsCount: 37,
    description: "Auriculares DJ compactos y plegables con gran relación calidad-precio para empezar a mezclar.",
    specs: [
      ["Driver", "40 mm"],
      ["Impedancia", "40 Ω"],
      ["Cable", "Desmontable, 1.5 m"],
      ["Plegable", "Sí"],
      ["Peso", "220 g"],
    ],
  },
  {
    id: "hd25", handle: "sennheiser-hd25", title: "Sennheiser HD 25 Auriculares DJ",
    vendor: "Sennheiser", category: "auriculares", price: 119, compareAtPrice: null,
    tags: ["auriculares", "dj", "Sennheiser"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/2/4/1/0/1200x1200_q100_png9_cr0_fix1/SennheiserHD25AuricularDJ-600da90bb4452.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/2/4/1/0/1200x1200_q100_png9_cr0_fix1/SennheiserHD25AuricularDJ-600da90bb4452.jpg"],
    optionName: "Color", options: [{ title: "Negro" }],
    rating: 4.9, reviewsCount: 210,
    description: "El clásico indestructible de cabina. Ligero, robusto y con un sonido cerrado muy fiable para mezclar.",
    specs: [
      ["Driver", "38 mm"],
      ["Impedancia", "70 Ω"],
      ["Peso", "140 g"],
      ["Cable", "1.5 m espiral"],
      ["Garantía", "2 años"],
    ],
  },
  {
    id: "cable-xlr", handle: "cable-xlr-profesional", title: "Cable XLR Profesional Macho-Hembra",
    vendor: "Victor So Pro", category: "cables", price: 19.9, compareAtPrice: null,
    tags: ["cables", "xlr"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/3/3/1200x1200_q100_png9_cr0_fix1/1.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/3/3/1200x1200_q100_png9_cr0_fix1/1.jpg"],
    optionName: "Longitud",
    options: [{ title: "3 metros", price: 14.9 }, { title: "6 metros", price: 19.9 }, { title: "10 metros", price: 27.9 }],
    rating: 4.7, reviewsCount: 65,
    description: "Cable XLR balanceado de calidad profesional, apantallado para eliminar ruidos e interferencias.",
    specs: [
      ["Conectores", "XLR macho/hembra"],
      ["Apantallamiento", "Trenzado de cobre"],
      ["Uso", "Micrófonos, línea balanceada"],
      ["Color", "Negro"],
    ],
  },
  {
    id: "cable-jack", handle: "cable-jack-jack", title: "Cable Jack 6.3mm TS Instrumento",
    vendor: "Victor So Pro", category: "cables", price: 12.9, compareAtPrice: null,
    tags: ["cables", "jack"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/3/1/1200x1200_q100_png9_cr0_fix1/1.webp", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/3/1/1200x1200_q100_png9_cr0_fix1/1.webp"],
    optionName: "Longitud",
    options: [{ title: "3 metros", price: 12.9 }, { title: "6 metros", price: 17.9 }],
    rating: 4.5, reviewsCount: 33,
    description: "Cable Jack-Jack mono de bajo ruido, ideal para conexión de línea y equipos DJ.",
    specs: [
      ["Conectores", "Jack 6.3mm TS"],
      ["Tipo", "Mono, no balanceado"],
      ["Uso", "Línea, instrumentos"],
      ["Color", "Negro"],
    ],
  },
  {
    id: "wpro-cdj", handle: "walkasse-wpro-cdj", title: "Walkasse WPRO-CDJ Flight Case Profesional",
    vendor: "Walkasse", category: "flightcases", price: 349, compareAtPrice: null,
    tags: ["flightcases", "proteccion", "Walkasse"],
    images: ["https://cloudflare.shopincdn.ovh/database_images_urls/9e/55/e5/9e55e510ee67ccb84f08fb0cecbcf150a40b8d80_226_226.jpg", "https://cloudflare.shopincdn.ovh/database_images_urls/9e/55/e5/9e55e510ee67ccb84f08fb0cecbcf150a40b8d80_226_226.jpg"],
    optionName: "Modelo compatible",
    options: [{ title: "CDJ-2000NXS2" }, { title: "CDJ-3000", price: 369 }],
    rating: 4.8, reviewsCount: 26,
    description: "Flight case de aluminio con espuma de corte a medida, protección total para transporte y giras.",
    specs: [
      ["Material", "Aluminio + contrachapado"],
      ["Interior", "Espuma troquelada"],
      ["Cierres", "Mariposa reforzados"],
      ["Peso", "6.2 kg"],
    ],
  },
  {
    id: "bag-controller", handle: "walkasse-bolsa-controller", title: "Walkasse Bolsa para Controlador DJ",
    vendor: "Walkasse", category: "flightcases", price: 89, compareAtPrice: null,
    tags: ["flightcases", "bolsas", "Walkasse"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/6/8/0/1200x1200_q100_png9_cr0_fix1/AlphaTheta-DJC-AN-BAG-2.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/6/8/0/1200x1200_q100_png9_cr0_fix1/AlphaTheta-DJC-AN-BAG-2.jpg"],
    optionName: "Talla",
    options: [{ title: "M (controladores compactos)" }, { title: "L (controladores grandes)", price: 109 }],
    rating: 4.6, reviewsCount: 19,
    description: "Bolsa acolchada resistente al agua con asa y correa de transporte, protección diaria para tu controlador.",
    specs: [
      ["Material", "Nylon 600D"],
      ["Acolchado", "10 mm EVA"],
      ["Bolsillos", "2 exteriores"],
      ["Resistencia", "Repelente al agua"],
    ],
  },
  {
    id: "ddjflx4-outlet", handle: "pioneer-dj-ddj-flx4-outlet", title: "Pioneer DJ DDJ-FLX4 Controlador (Outlet - Caja Abierta)",
    vendor: "Pioneer DJ", category: "outlet", price: 279, compareAtPrice: 349,
    tags: ["outlet", "dj", "Pioneer DJ", "oferta"],
    images: ["https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/6/8/1200x1200_q100_png9_cr0_fix1/alphatheta-euphonia1.jpg", "https://cloudflare.shopincdn.ovh/victorso/cache/images/_product_catalogue_/4/5/6/8/1200x1200_q100_png9_cr0_fix1/alphatheta-euphonia1.jpg"],
    optionName: "Formato", options: [{ title: "Unidad individual" }],
    rating: 4.5, reviewsCount: 14,
    description: "Unidad de exposición en perfecto estado, caja abierta, con todos los accesorios y garantía completa.",
    specs: [
      ["Estado", "Caja abierta / exposición"],
      ["Garantía", "2 años"],
      ["Canales", "2"],
      ["Software", "rekordbox + Serato"],
    ],
  },
];

const REVIEW_AUTHORS = ["Marc R.", "Laura G.", "Iván P.", "Sofía M.", "David T.", "Elena C.", "Jordi V.", "Nuria S."];
const REVIEW_TEXTS = [
  "Justo lo que necesitaba, calidad profesional y envío rapidísimo.",
  "Muy buen sonido, se nota que es material de nivel profesional.",
  "Llegó perfectamente embalado y antes de lo esperado.",
  "Relación calidad-precio excelente, lo recomiendo sin duda.",
  "Atención al cliente estupenda, resolvieron mis dudas antes de comprar.",
  "Se nota la diferencia frente a equipos de gama más baja.",
  "Segunda compra en la tienda, siempre cumplen lo que prometen.",
  "Ideal para uso profesional en cabina, muy satisfecho.",
];

function seededReviews(product) {
  const count = Math.min(4, Math.max(2, Math.round(product.reviewsCount / 30)));
  return Array.from({ length: count }).map((_, i) => ({
    author: REVIEW_AUTHORS[(product.id.length + i) % REVIEW_AUTHORS.length],
    rating: Math.max(3, Math.min(5, Math.round(product.rating) - (i % 2))),
    text: REVIEW_TEXTS[(product.id.length + i * 3) % REVIEW_TEXTS.length],
    date: new Date(2026, (i * 2 + 1) % 12, ((product.id.length * (i + 1)) % 27) + 1).toLocaleDateString("es-ES"),
  }));
}

/** Mapeo de nuestra `category` (interna, usada para rutas /category/:slug)
 * al `productType` que expondría Shopify — son dos campos distintos en
 * Storefront API (productType es libre; las categorías reales de la
 * tienda serían Collections, no un campo del producto). */
const CATEGORY_TO_PRODUCT_TYPE = {
  dj: "Equipos DJ", sonido: "Sonido Profesional", estudio: "Material de Estudio",
  auriculares: "Auriculares", cables: "Cables", flightcases: "Flight-Cases y Bolsas", outlet: "Outlet",
};

/** PRODUCTS: forma final consumida por app.js, análoga a Shopify Storefront API.
 * `available` se mantiene como nombre interno (así queda el resto del código),
 * pero se añade `availableForSale` — el nombre real del campo en Storefront API —
 * para que la migración futura sea un simple find&replace. */
const PRODUCTS = RAW_PRODUCTS.map((p) => {
  const variants = buildVariants(p, p.options).map((v) => ({ ...v, availableForSale: v.available }));
  const withReviews = {
    ...p,
    variants,
    productType: CATEGORY_TO_PRODUCT_TYPE[p.category] || p.category,
    currencyCode: "EUR",
  };
  return { ...withReviews, reviews: seededReviews(withReviews) };
});

const TESTIMONIALS = [
  { author: "Àlex Ferrer", role: "DJ residente, Sala Nexus", text: "Compro todo mi material aquí desde hace años. Asesoramiento real de gente que sabe de cabina.", rating: 5 },
  { author: "Cristina Boix", role: "Técnica de sonido freelance", text: "Envíos rápidos y equipos siempre originales con garantía. Mi tienda de confianza para giras.", rating: 5 },
  { author: "Marc Oliveras", role: "Productor musical", text: "El material de estudio que venden es de primer nivel y los precios muy competitivos.", rating: 4 },
];

/** Proyectos de instalación realizados (servicio técnico, no venta online).
 * Añadir más simplemente empujando un objeto nuevo a este array. */
const INSTALLATIONS = [
  {
    title: "Sonorización del Paseo Marítimo de Lloret de Mar",
    location: "Lloret de Mar (Girona)",
    image: "assets/instalacion-paseo-maritimo.jpeg",
    description: "Megafonía integrada en el propio alumbrado público: altavoces instalados en las farolas a lo largo de todo el paseo marítimo, con cobertura sonora uniforme de punta a punta. El ayuntamiento la usa para avisos municipales, música ambiente y la locución/sonido de eventos como el Drone Festival, garantizando una escucha nítida en toda la longitud del paseo sin puntos ciegos.",
  },
];
